import React from 'react'

function PrivacyPolicy() {
  return (
    <div className="p-6 sm:p-12 md:p-16 lg:p-20 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold mb-6 text-center">Privacy Policy</h1>
      <p className="text-gray-600 mb-4">Last updated: December 16, 2024</p>

      <p className="text-gray-700 mb-6">
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
        information when You use the Service and explains Your privacy rights and how the law protects You.
      </p>

      <p className="text-gray-700 mb-6">
        We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection
        and use of information in accordance with this Privacy Policy.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>

        <h3 className="text-xl font-medium mb-2">Interpretation</h3>
        <p className="text-gray-700 mb-4">
          The Words with their initial letter capitalized have meanings defined under the following conditions. The
          following definitions apply regardless of whether they appear in singular or plural form.
        </p>

        <h3 className="text-xl font-medium mb-2">Definitions</h3>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li>
            <strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.
          </li>
          <li>
            <strong>Company:</strong> Refers to EditWithSanjay.in ("We," "Us," or "Our" in this Agreement).
          </li>
          <li>
            <strong>Cookies:</strong> Small files placed on Your device by a website, containing details of Your browsing
            history, among other uses.
          </li>
          <li>
            <strong>Country:</strong> Refers to India.
          </li>
          <li>
            <strong>Device:</strong> Any device that can access the Service, such as a computer, cellphone, or tablet.
          </li>
          <li>
            <strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>Service:</strong> Refers to the Website.
          </li>
          <li>
            <strong>Service Provider:</strong> Any natural or legal person who processes data on behalf of the Company.
          </li>
          <li>
            <strong>Third-party Social Media Service:</strong> Any social network or website allowing a User to log in or
            create an account to use the Service.
          </li>
          <li>
            <strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or its
            infrastructure.
          </li>
          <li>
            <strong>Website:</strong> Refers to EditWithSanjay.in, accessible from https://editwithsanjay.in.
          </li>
          <li>
            <strong>You:</strong> The individual accessing or using the Service, or the company or legal entity on whose
            behalf the Service is being accessed.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-medium mb-2">Types of Data Collected</h3>

        <h4 className="text-lg font-medium mb-2">Personal Data</h4>
        <p className="text-gray-700 mb-4">
          While using Our Service, We may ask You to provide certain personally identifiable information to contact or
          identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-medium mb-2">Usage Data</h4>
        <p className="text-gray-700 mb-4">
          Usage Data is collected automatically during Your use of the Service. This may include information such as:
        </p>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li>Your Device’s Internet Protocol (IP) address</li>
          <li>Browser type and version</li>
          <li>Pages visited, time and date of visit, time spent on pages</li>
          <li>Unique device identifiers and diagnostic data</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Tracking Technologies and Cookies</h2>
        <p className="text-gray-700 mb-4">
          We use Cookies and similar tracking technologies (e.g., beacons, tags, scripts) to analyze and improve our
          Service.
        </p>

        <h3 className="text-xl font-medium mb-2">Types of Cookies We Use</h3>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li>
            <strong>Necessary / Essential Cookies:</strong> Ensure basic functionalities like account authentication and
            fraud prevention.
          </li>
          <li>
            <strong>Cookies Policy / Notice Acceptance Cookies:</strong> Identify if You’ve accepted our cookies.
          </li>
          <li>
            <strong>Functionality Cookies:</strong> Remember preferences, such as login details or language settings.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
        <p className="text-gray-700">
          If You have any questions about this Privacy Policy, please reach out via our
          <a
            href="/contact-us"
            className="text-blue-600 hover:underline ml-1"
          >
            Contact Us
          </a>
          page.
        </p>
      </section>
    </div>
  )
}

export default PrivacyPolicy

